// Metadata for this route is generated by the real Next.js route file:
// src/app/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React from "react";
import AquaMistHero from "./components/Hero";
import AquaMistHomeContent from "./components/HomeContent";

/**
 * AquaMist theme — Home Page
 *
 * Renders the Hero section and the home page content sections
 * (Features, Best Sellers, Press Strip) which are defined as
 * separate components in the ./components/ folder.
 *
 * This page is intended to be mounted via the root layout once
 * the theme-switching logic routes to `aquamist`. Until then it
 * can be previewed by pointing the root page.tsx at this component.
 */
export default function AquaMistHomePage() {
  return (
    <>
      <AquaMistHero />
      <AquaMistHomeContent />
    </>
  );
}
