// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/checkout/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React, { Suspense } from "react";
import AquaMistCheckoutContent from "@/themes/aquamist/components/CheckoutContent";
import { AuthModal } from "@/components/AuthModal";

export default function AquaMistCheckoutPage() {
  return (
    <Suspense fallback={<div className="pt-32 text-center text-aq-on-surface-variant font-inter">Loading checkout…</div>}>
      <AquaMistCheckoutContent />
      <AuthModal from="checkout" />
    </Suspense>
  );
}

