// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/profile/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React from "react";
import AquaMistProfileOverviewContent from "@/themes/aquamist/components/ProfileOverviewContent";

export default function AquaMistProfilePage() {
  return <AquaMistProfileOverviewContent />;
}
