// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/collections/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React, { Suspense } from "react";
import AquaMistCollectionsContent from "@/themes/aquamist/components/CollectionsContent";

export default function AquaMistCollectionsPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#0A0F1E]" />}>
      <AquaMistCollectionsContent />
    </Suspense>
  );
}
