// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/cart/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React from "react";
import AquaMistCartContent from "@/themes/aquamist/components/CartContent";

/**
 * AquaMist Cart page route.
 *
 * Thin server-component wrapper that renders the interactive
 * client component for the cart screen.
 */
export default function AquaMistCartPage() {
  return <AquaMistCartContent />;
}
