// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/product-detail/[slug]/page.tsx (or its metadata.ts).
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React from "react";
import AquaMistProductDetailContent from "@/themes/aquamist/components/ProductDetailContent";

interface PageProps {
  params: {
    slug: string;
  };
}

/**
 * AquaMist Product Detail page route component.
 *
 * Renders the theme-specific AquaMistProductDetailContent client component
 * passing the dynamic slug from Next.js dynamic routing.
 */
export default function AquaMistProductDetailPage({ params: { slug } }: PageProps) {
  return <AquaMistProductDetailContent slug={slug} />;
}
