import type { Metadata } from "next";
import { Jost } from "next/font/google"; // Import Jost instead of Inter
import "./globals.css";
import Navbar from "@/components/Nav";
import Footer from "@/components/Footer/footer";
import StoreTypeProviderWrapper from "@/Context/StoreTypeProviderWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import Provider from "@/Context/react-query-provider";
import { SelectedCategoryProvider } from "@/components/Trending/context/SelectedCategoryContext";

// const jost = Jost({ subsets: ["latin"] }); // Load the Jost font

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify weights if needed
  style: ["normal", "italic"], // Optional: Include both normal and italic styles
});

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Provider>
          <StoreTypeProviderWrapper>
            <ToastContainer
              autoClose={1000}
              theme="colored"
              position="top-right"
            />
            <Navbar />
            {children}
            <Footer />
            <ReactQueryDevtools initialIsOpen={false} />
          </StoreTypeProviderWrapper>
        </Provider>
      </body>
    </html>
  );
}
