import type { Metadata } from "next";
import { Jost } from "next/font/google"; // Import Jost instead of Inter
import "./globals.css";
import Navbar from "@/components/Nav";

const jost = Jost({ subsets: ["latin"] }); // Load the Jost font

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}> {/* Apply Jost font class */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
