// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/profile/order-details/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React from "react";
import AquaMistProfileOrderDetailsContent from "@/themes/aquamist/components/ProfileOrderDetailsContent";

export default function AquaMistOrderDetailsPage() {
  return <AquaMistProfileOrderDetailsContent />;
}
