// Metadata for this route is generated by the real Next.js route file:
// src/app/(pages)/order-confirmation/page.tsx.
// This file is a plain component, not a route — any metadata export here
// is never executed by Next.js.

import React, { Suspense } from "react";
import AquaMistOrderConfirmationContent from "@/themes/aquamist/components/OrderConfirmationContent";

export default function AquaMistOrderConfirmationPage() {
  return (
    <Suspense fallback={<div className="min-h-screen pt-32 text-center text-aq-on-surface-variant font-inter">Loading order details…</div>}>
      <AquaMistOrderConfirmationContent />
    </Suspense>
  );
}
